POST http://localhost:8085/chatting HTTP/1.1
Content-Type: application/json

{
    "itemId":"d4c02e9b-1497-48df-885e-6ba6426e73d2",
    "sellerId":"seller@directdeal.co.kr",
    "customerId":"customer@directdeal.co.kr"
}


###

PUT http://localhost:8085/chatting HTTP/1.1
Content-Type: application/json

{
    "id":"1",
    "newMessage": {
        "talkerId":"customer@directdeal.co.kr",
        "text":"문의 드립니다."
    }
}

###

GET http://localhost:8085/chatting HTTP/1.1
Content-Type: application/json

{
    "itemId":"d4c02e9b-1497-48df-885e-6ba6426e73d2",
    "sellerId":"seller@directdeal.co.kr",
    "customerId":"customer@directdeal.co.kr"
}

###

PUT http://localhost:8085/chatting HTTP/1.1
Content-Type: application/json

{
    "id":"1",
    "newMessage": {
        "talkerId":"seller@directdeal.co.kr",
        "text":"네 말씀하세요."
    }
}

###

GET http://localhost:8085/chatting/1 HTTP/1.1

###

POST http://localhost:8085/chatting HTTP/1.1
Content-Type: application/json

{
    "itemId":"d4c02e9b-1497-48df-885e-6ba6426e73d2",
    "sellerId":"seller@directdeal.co.kr",
    "customerId":"customer2@directdeal.co.kr"
}

###

POST http://localhost:8085/chatting HTTP/1.1
Content-Type: application/json

{
    "itemId":"d4c02e9b-1497-48df-885e-6ba6426e73d2",
    "sellerId":"seller@directdeal.co.kr",
    "customerId":"customer2@directdeal.co.kr"
}

###

POST http://localhost:8085/chatting HTTP/1.1
Content-Type: application/json

{
    "itemId":"d4c02e9b-1497-48df-885e-6ba6426e73d2",
    "sellerId":"seller@directdeal.co.kr",
    "customerId":"customer3@directdeal.co.kr"
}

###

POST http://localhost:8085/chatting HTTP/1.1
Content-Type: application/json

{
    "itemId":"d4c02e9b-1497-48df-885e-6ba6426e73d2",
    "sellerId":"seller@directdeal.co.kr",
    "customerId":"customer4@directdeal.co.kr"
}

###

GET http://localhost:8085/chatting/d4c02e9b-1497-48df-885e-6ba6426e73d2/customer-list HTTP/1.1


