POST http://localhost:8080/account HTTP/1.1
Content-Type: application/json

{
    "email":"account@directdeal.co.kr",
    "name":"account",
    "password":"1q2w3e"
}

###

POST http://localhost:8080/auth/login HTTP/1.1
Content-Type: application/json

{
    "email":"account@directdeal.co.kr",
    "password":"1q2w3e"
}

###

GET http://localhost:8080/account HTTP/1.1

###

GET http://localhost:8080/account HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhY2NvdW50QGRpcmVjdGRlYWwuY28ua3IiLCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUiIsImV4cCI6MTYyMzcxODkyMH0.AzQYYAX5oV0ATVfAUMN0Nk0EJ_GhOeO0uPbykDeLnnnOj-_xdBi3iqb6JdNSYj5GbaSvMLzqyqkHCFdcoOgUOQ

###

PUT http://localhost:8080/account HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhY2NvdW50QGRpcmVjdGRlYWwuY28ua3IiLCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUiIsImV4cCI6MTYyMzcxODkyMH0.AzQYYAX5oV0ATVfAUMN0Nk0EJ_GhOeO0uPbykDeLnnnOj-_xdBi3iqb6JdNSYj5GbaSvMLzqyqkHCFdcoOgUOQ
Content-Type: application/json

{
    "email":"account@directdeal.co.kr",
    "name":"rick"
}

###

PUT http://localhost:8080/account/change-password HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhY2NvdW50QGRpcmVjdGRlYWwuY28ua3IiLCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUiIsImV4cCI6MTYyMzcxODkyMH0.AzQYYAX5oV0ATVfAUMN0Nk0EJ_GhOeO0uPbykDeLnnnOj-_xdBi3iqb6JdNSYj5GbaSvMLzqyqkHCFdcoOgUOQ
Content-Type: application/json

{
    "password":"1q2w3e",
    "newPassword":"123qwe"
}

###

POST http://localhost:8080/auth/login HTTP/1.1
Content-Type: application/json

{
    "email":"account@directdeal.co.kr",
    "password":"123qwe"
}

###

DELETE http://localhost:8080/account HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhY2NvdW50QGRpcmVjdGRlYWwuY28ua3IiLCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUiIsImV4cCI6MTYyMzcxODkyMH0.AzQYYAX5oV0ATVfAUMN0Nk0EJ_GhOeO0uPbykDeLnnnOj-_xdBi3iqb6JdNSYj5GbaSvMLzqyqkHCFdcoOgUOQ

###

