apiVersion: v1
kind: Service
metadata:
  name: gateway
  # namespace: default
  labels:
    app: gateway
spec:
  ports:
  - name: httpport
    port: 8084
    protocol: TCP
    targetPort: 8084
  selector:
    app: gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  # namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
      version: 'v1'
  template:
    metadata:
      labels:
        app: gateway
        version: 'v1'
    spec:
      containers:
      - name: gateway
        image: localhost:5000/direct-deal-gateway:latest
        imagePullPolicy: Always
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        ports:
        - containerPort: 8084
          name: httpport
        # resources:
        #     # requests:
        #     #   memory: '512Mi'
        #     #   cpu: '500m'
        #     limits:
        #       memory: '256Mi'
        #       # cpu: '100m'
        # livenessProbe:
        #   httpGet:
        #     path: /actuator/health
        #     port: 8084
        #   initialDelaySeconds: 30
        #   periodSeconds: 20
        #   failureThreshold: 20
        # readinessProbe:
        #   httpGet:
        #     path: /actuator/health
        #     port: 8084
        #   initialDelaySeconds: 30
        #   periodSeconds: 20
        #   failureThreshold: 20
---
