apiVersion: v1
kind: Service
metadata:
  name: chatting-service
  # namespace: default
  labels:
    app: chatting-service
spec:
  ports:
  - name: httpport
    port: 8085
    protocol: TCP
    targetPort: 8085
  selector:
    app: chatting-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatting-service
  # namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatting-service
      version: 'v1'
  # strategy:
  #   rollingUpdate:
  #     maxUnavailable: 0
  template:
    metadata:
      labels:
        app: chatting-service
        version: 'v1'
    spec:
      initContainers:
        - name: init-ds
          image: busybox:latest
          command:
            - '/bin/sh'
            - '-c'
            - |
              while true
              do
                rt=$(nc -z -w 1 mysql 3306)
                if [ $? -eq 0 ]; then
                  echo "DB is UP"
                  break
                fi
                echo "DB is not yet reachable;sleep for 10s before retry"
                sleep 10
              done
      containers:
      - name: chatting-service
        image: direct-deal-chatting-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8085
          name: httpport
        # resources:
        #     # requests:
        #     #   memory: '512Mi'
        #     #   cpu: '500m'
        #     limits:
        #       memory: '256Mi'
        #       # cpu: '100m'
        # livenessProbe:
        #   httpGet:
        #     path: /actuator/health
        #     port: 8085
        #   initialDelaySeconds: 30
        #   periodSeconds: 20
        #   failureThreshold: 20
        # readinessProbe:
        #   httpGet:
        #     path: /actuator/health
        #     port: 8085
        #   initialDelaySeconds: 30
        #   periodSeconds: 20
        #   failureThreshold: 20
---
