apiVersion: v1
kind: Service
metadata:
  name: transaction-history-service
  # namespace: default
  labels:
    app: transaction-history-service
spec:
  ports:
  - name: httpport
    port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    app: transaction-history-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-history-service
  # namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-history-service
      version: 'v1'
  template:
    metadata:
      labels:
        app: transaction-history-service
        version: 'v1'
    spec:
      initContainers:
      - name: init-ds
        image: busybox:latest
        command:
          - '/bin/sh'
          - '-c'
          - |
            while true
            do
              rt=$(nc -z -w 1 mysql 3306 && nc -z -w 1 kafka 9092)
              if [ $? -eq 0 ]; then
                echo "DB is UP"
                break
              fi
              echo "DB is not yet reachable;sleep for 10s before retry"
              sleep 10
            done
      containers:
      - name: transaction-history-service
        image: localhost:5000/direct-deal-transaction-history-service:latest
        imagePullPolicy: Always
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        ports:
        - containerPort: 8083
          name: httpport
        # resources:
        #     # requests:
        #     #   memory: '512Mi'
        #     #   cpu: '500m'
        #     limits:
        #       memory: '256Mi'
        #       # cpu: '100m'
        # livenessProbe:
        #   httpGet:
        #     path: /actuator/health
        #     port: 8083
        #   initialDelaySeconds: 30
        #   periodSeconds: 20
        #   failureThreshold: 20
        # readinessProbe:
        #   httpGet:
        #     path: /actuator/health
        #     port: 8083
        #   initialDelaySeconds: 30
        #   periodSeconds: 20
        #   failureThreshold: 20
---
