apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
  - name: mysqlport
    port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      version: 'v1'
  template:
    metadata:
      labels:
        app: mysql
        version: 'v1'
    spec:
      containers:
      - name: mysql
        image: gcr.io/${PROJECT_ID}/direct-deal-mysql:${REVISION_ID}
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
          name: mysqlport
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "secret"
          - name: PROJECT_ID
            value: "${PROJECT_ID}"
        # resources:
        #     # requests:
        #     #   memory: '512Mi'
        #     #   cpu: '500m'
        #     limits:
        #       memory: '256Mi'
        #       # cpu: '100m'
---
