apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
  - name: redisport
    port: 6379
    targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      version: 'v1'
  template:
    metadata:
      labels:
        app: redis
        version: 'v1'
    spec:
      containers:
      - name: redis
        image: redis:6.2.4-alpine3.13
        ports:
        - containerPort: 6379
          name: redisport
        # resources:
        #     # requests:
        #     #   memory: '512Mi'
        #     #   cpu: '500m'
        #     limits:
        #       memory: '256Mi'
        #       # cpu: '100m'
---
