GET http://localhost:8084/api/v1/actuator/beans HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXJAZGlyZWN0ZGVhbC5jby5rciIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjIzODg4NzQwfQ.wcfz3m8A9Atu_W44WfOZQ1_uDJsrAtOhkzPHPLAdnlkNLr-jGuy3zdqiavHf8aRqkoAqBOd1uX6NDLEdSNMAaQ

### Create an account

POST http://localhost:8084/api/v1/account HTTP/1.1
Content-Type: application/json

{
    "email":"seller@directdeal.co.kr",
    "name":"seller",
    "password":"1q2w3e"
}

### login and get an access token

POST http://localhost:8084/api/v1/auth/login HTTP/1.1
Content-Type: application/json

{
    "email":"seller@directdeal.co.kr",
    "password":"1q2w3e"
}

###

POST http://localhost:8084/api/v1/image HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXJAZGlyZWN0ZGVhbC5jby5rciIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjIzODg4NzQwfQ.wcfz3m8A9Atu_W44WfOZQ1_uDJsrAtOhkzPHPLAdnlkNLr-jGuy3zdqiavHf8aRqkoAqBOd1uX6NDLEdSNMAaQ
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="files"; filename="1.jpg"
Content-Type: image/jpg; image/png; image/gif;

< ../samples/1.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

GET http://localhost:8084/api/v1/image/check-upload-status/896c63a3-f9fc-4c39-af09-cb9c5566ad9f HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXJAZGlyZWN0ZGVhbC5jby5rciIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjIzODg4NzQwfQ.wcfz3m8A9Atu_W44WfOZQ1_uDJsrAtOhkzPHPLAdnlkNLr-jGuy3zdqiavHf8aRqkoAqBOd1uX6NDLEdSNMAaQ

###

GET http://localhost:8084/api/v1/image/13934d49-f106-4c0f-a98f-25e630e65ac8.jpg HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXJAZGlyZWN0ZGVhbC5jby5rciIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjIzODg4NzQwfQ.wcfz3m8A9Atu_W44WfOZQ1_uDJsrAtOhkzPHPLAdnlkNLr-jGuy3zdqiavHf8aRqkoAqBOd1uX6NDLEdSNMAaQ

