POST http://localhost:8084/api/v1/favorite HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXJAZGlyZWN0ZGVhbC5jby5rciIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjIzODg4NzQwfQ.wcfz3m8A9Atu_W44WfOZQ1_uDJsrAtOhkzPHPLAdnlkNLr-jGuy3zdqiavHf8aRqkoAqBOd1uX6NDLEdSNMAaQ
Content-Type: application/json

{
    "itemId":"80b1616d-c8a8-47f3-80bb-20926444974c"
}

###

GET http://localhost:8084/api/v1/favorite HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXJAZGlyZWN0ZGVhbC5jby5rciIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjIzODg4NzQwfQ.wcfz3m8A9Atu_W44WfOZQ1_uDJsrAtOhkzPHPLAdnlkNLr-jGuy3zdqiavHf8aRqkoAqBOd1uX6NDLEdSNMAaQ

###

DELETE http://localhost:8084/api/v1/favorite/80b1616d-c8a8-47f3-80bb-20926444974c HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXJAZGlyZWN0ZGVhbC5jby5rciIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjIzODg4NzQwfQ.wcfz3m8A9Atu_W44WfOZQ1_uDJsrAtOhkzPHPLAdnlkNLr-jGuy3zdqiavHf8aRqkoAqBOd1uX6NDLEdSNMAaQ