POST http://localhost:8084/api/v1/favorite HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXJAZGlyZWN0ZGVhbC5jby5rciIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjI0ODU5MzMzfQ._cWRCBz5RFlajgvmq2rHYpN3GuGhcbVy4ZmAFUMzxUdTYjA0MNdfK-cIcKxWD2-Znnrqgt9_nzVNlwLOBNfDww
Content-Type: application/json

{
    "itemId":"80b1616d-c8a8-47f3-80bb-20926444974c"
}

###

GET http://localhost:8084/api/v1/favorite HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXJAZGlyZWN0ZGVhbC5jby5rciIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjI0ODU5MzMzfQ._cWRCBz5RFlajgvmq2rHYpN3GuGhcbVy4ZmAFUMzxUdTYjA0MNdfK-cIcKxWD2-Znnrqgt9_nzVNlwLOBNfDww

###

DELETE http://localhost:8084/api/v1/favorite/80b1616d-c8a8-47f3-80bb-20926444974c HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXJAZGlyZWN0ZGVhbC5jby5rciIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjI0ODU5MzMzfQ._cWRCBz5RFlajgvmq2rHYpN3GuGhcbVy4ZmAFUMzxUdTYjA0MNdfK-cIcKxWD2-Znnrqgt9_nzVNlwLOBNfDww