POST http://localhost:8084/api/v1/category HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXJAZGlyZWN0ZGVhbC5jby5rciIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjI0ODU5MzMzfQ._cWRCBz5RFlajgvmq2rHYpN3GuGhcbVy4ZmAFUMzxUdTYjA0MNdfK-cIcKxWD2-Znnrqgt9_nzVNlwLOBNfDww

{
    "name":"Appliances"
}

###

GET http://localhost:8084/api/v1/category HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXJAZGlyZWN0ZGVhbC5jby5rciIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjI0ODU5MzMzfQ._cWRCBz5RFlajgvmq2rHYpN3GuGhcbVy4ZmAFUMzxUdTYjA0MNdfK-cIcKxWD2-Znnrqgt9_nzVNlwLOBNfDww

###

POST http://localhost:8084/api/v1/category HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXJAZGlyZWN0ZGVhbC5jby5rciIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjI0ODU5MzMzfQ._cWRCBz5RFlajgvmq2rHYpN3GuGhcbVy4ZmAFUMzxUdTYjA0MNdfK-cIcKxWD2-Znnrqgt9_nzVNlwLOBNfDww

{
    "name":"Food"
}

###

GET http://localhost:8084/api/v1/category HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXJAZGlyZWN0ZGVhbC5jby5rciIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjI0ODU5MzMzfQ._cWRCBz5RFlajgvmq2rHYpN3GuGhcbVy4ZmAFUMzxUdTYjA0MNdfK-cIcKxWD2-Znnrqgt9_nzVNlwLOBNfDww

###

POST http://localhost:8084/api/v1/category HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXJAZGlyZWN0ZGVhbC5jby5rciIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjI0ODU5MzMzfQ._cWRCBz5RFlajgvmq2rHYpN3GuGhcbVy4ZmAFUMzxUdTYjA0MNdfK-cIcKxWD2-Znnrqgt9_nzVNlwLOBNfDww

{
    "name":"Computer",
    "parent": {"id":"1"}
}

###

GET http://localhost:8084/api/v1/category HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXJAZGlyZWN0ZGVhbC5jby5rciIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjI0ODU5MzMzfQ._cWRCBz5RFlajgvmq2rHYpN3GuGhcbVy4ZmAFUMzxUdTYjA0MNdfK-cIcKxWD2-Znnrqgt9_nzVNlwLOBNfDww

###

POST http://localhost:8084/api/v1/category HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXJAZGlyZWN0ZGVhbC5jby5rciIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjI0ODU5MzMzfQ._cWRCBz5RFlajgvmq2rHYpN3GuGhcbVy4ZmAFUMzxUdTYjA0MNdfK-cIcKxWD2-Znnrqgt9_nzVNlwLOBNfDww
Content-Type: application/json

{
    "name":"NoteBook",
    "parent": {"id":"3"}
}

###

GET http://localhost:8084/api/v1/category HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXJAZGlyZWN0ZGVhbC5jby5rciIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjI0ODU5MzMzfQ._cWRCBz5RFlajgvmq2rHYpN3GuGhcbVy4ZmAFUMzxUdTYjA0MNdfK-cIcKxWD2-Znnrqgt9_nzVNlwLOBNfDww

###

PUT http://localhost:8084/api/v1/category HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXJAZGlyZWN0ZGVhbC5jby5rciIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjI0ODU5MzMzfQ._cWRCBz5RFlajgvmq2rHYpN3GuGhcbVy4ZmAFUMzxUdTYjA0MNdfK-cIcKxWD2-Znnrqgt9_nzVNlwLOBNfDww
Content-Type: application/json

{
    "id":"4",
    "name":"iPad",
    "parent": {"id":"3"}
}

###

GET http://localhost:8084/api/v1/category HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXJAZGlyZWN0ZGVhbC5jby5rciIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjI0ODU5MzMzfQ._cWRCBz5RFlajgvmq2rHYpN3GuGhcbVy4ZmAFUMzxUdTYjA0MNdfK-cIcKxWD2-Znnrqgt9_nzVNlwLOBNfDww

###

PUT http://localhost:8084/api/v1/category HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXJAZGlyZWN0ZGVhbC5jby5rciIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjI0ODU5MzMzfQ._cWRCBz5RFlajgvmq2rHYpN3GuGhcbVy4ZmAFUMzxUdTYjA0MNdfK-cIcKxWD2-Znnrqgt9_nzVNlwLOBNfDww
Content-Type: application/json

{
    "id":"1",
    "name":"Appliances"
}

###

GET http://localhost:8084/api/v1/category HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXJAZGlyZWN0ZGVhbC5jby5rciIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjI0ODU5MzMzfQ._cWRCBz5RFlajgvmq2rHYpN3GuGhcbVy4ZmAFUMzxUdTYjA0MNdfK-cIcKxWD2-Znnrqgt9_nzVNlwLOBNfDww

###

DELETE http://localhost:8084/api/v1/category/4 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXJAZGlyZWN0ZGVhbC5jby5rciIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjI0ODU5MzMzfQ._cWRCBz5RFlajgvmq2rHYpN3GuGhcbVy4ZmAFUMzxUdTYjA0MNdfK-cIcKxWD2-Znnrqgt9_nzVNlwLOBNfDww

###

GET http://localhost:8084/api/v1/category HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXJAZGlyZWN0ZGVhbC5jby5rciIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjI0ODU5MzMzfQ._cWRCBz5RFlajgvmq2rHYpN3GuGhcbVy4ZmAFUMzxUdTYjA0MNdfK-cIcKxWD2-Znnrqgt9_nzVNlwLOBNfDww

###

DELETE http://localhost:8084/api/v1/category/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXJAZGlyZWN0ZGVhbC5jby5rciIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjI0ODU5MzMzfQ._cWRCBz5RFlajgvmq2rHYpN3GuGhcbVy4ZmAFUMzxUdTYjA0MNdfK-cIcKxWD2-Znnrqgt9_nzVNlwLOBNfDww

###

GET http://localhost:8084/api/v1/category HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXJAZGlyZWN0ZGVhbC5jby5rciIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjI0ODU5MzMzfQ._cWRCBz5RFlajgvmq2rHYpN3GuGhcbVy4ZmAFUMzxUdTYjA0MNdfK-cIcKxWD2-Znnrqgt9_nzVNlwLOBNfDww

###

DELETE http://localhost:8084/api/v1/category/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXJAZGlyZWN0ZGVhbC5jby5rciIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjI0ODU5MzMzfQ._cWRCBz5RFlajgvmq2rHYpN3GuGhcbVy4ZmAFUMzxUdTYjA0MNdfK-cIcKxWD2-Znnrqgt9_nzVNlwLOBNfDww

###

GET http://localhost:8084/api/v1/category HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXJAZGlyZWN0ZGVhbC5jby5rciIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjI0ODU5MzMzfQ._cWRCBz5RFlajgvmq2rHYpN3GuGhcbVy4ZmAFUMzxUdTYjA0MNdfK-cIcKxWD2-Znnrqgt9_nzVNlwLOBNfDww

###