POST http://localhost:8084/api/v1/account HTTP/1.1
Content-Type: application/json

{
    "email":"account@directdeal.co.kr",
    "name":"account",
    "password":"1q2w3e"
}

###

POST http://localhost:8084/api/v1/auth/login HTTP/1.1
Content-Type: application/json

{
    "email":"account@directdeal.co.kr",
    "password":"1q2w3e"
}

###

GET http://localhost:8084/api/v1/account HTTP/1.1

###

GET http://localhost:8084/api/v1/account HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhY2NvdW50QGRpcmVjdGRlYWwuY28ua3IiLCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUiIsImV4cCI6MTYyNDg2NDE0NH0.OWiP55gGSiezOFO2phMw5CmuzbVb_6fGJNQ-MzLJye9VkOIQ_JHRciHW6IqJlqYYzqXpVJst96XK0eHXHTwAwA

###

PUT http://localhost:8084/api/v1/account HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhY2NvdW50QGRpcmVjdGRlYWwuY28ua3IiLCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUiIsImV4cCI6MTYyNDg2NDE0NH0.OWiP55gGSiezOFO2phMw5CmuzbVb_6fGJNQ-MzLJye9VkOIQ_JHRciHW6IqJlqYYzqXpVJst96XK0eHXHTwAwA
Content-Type: application/json

{
    "email":"account@directdeal.co.kr",
    "name":"user"
}

###

PUT http://localhost:8084/api/v1/account/change-password HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhY2NvdW50QGRpcmVjdGRlYWwuY28ua3IiLCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUiIsImV4cCI6MTYyNDg2NDE0NH0.OWiP55gGSiezOFO2phMw5CmuzbVb_6fGJNQ-MzLJye9VkOIQ_JHRciHW6IqJlqYYzqXpVJst96XK0eHXHTwAwA
Content-Type: application/json

{
    "password":"1q2w3e",
    "newPassword":"123qwe"
}

###

POST http://localhost:8084/api/v1/auth/login HTTP/1.1
Content-Type: application/json

{
    "email":"account@directdeal.co.kr",
    "password":"123qwe"
}

###

DELETE http://localhost:8084/api/v1/account HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhY2NvdW50QGRpcmVjdGRlYWwuY28ua3IiLCJhdXRob3JpdGllcyI6IlJPTEVfVVNFUiIsImV4cCI6MTYyNDg2NDE0NH0.OWiP55gGSiezOFO2phMw5CmuzbVb_6fGJNQ-MzLJye9VkOIQ_JHRciHW6IqJlqYYzqXpVJst96XK0eHXHTwAwA

###

