### Create an account

POST http://localhost:8080/account HTTP/1.1
Content-Type: application/json

{
    "email":"seller@directdeal.co.kr",
    "name":"seller",
    "password":"1q2w3e"
}

### login and get an access token

POST http://localhost:8080/auth/login HTTP/1.1
Content-Type: application/json

{
    "email":"seller@directdeal.co.kr",
    "password":"1q2w3e"
}

###

GET http://localhost:8083/transaction-history HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXJAZGlyZWN0ZGVhbC5jby5rciIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjIzMzM0MDUxfQ.wP_A8Ap4Nh-3LhghhcHRlGLggOfcmdzCFfttcQLwYOY4Ye2RTbyvSzLMG6aD2p0QE4_I67R6E7g-KjxbgtBiiA

###

PUT http://localhost:8083/transaction-history/setbuyer HTTP/1.1
Content-Type : application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXJAZGlyZWN0ZGVhbC5jby5rciIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjIzMzM0MDUxfQ.wP_A8Ap4Nh-3LhghhcHRlGLggOfcmdzCFfttcQLwYOY4Ye2RTbyvSzLMG6aD2p0QE4_I67R6E7g-KjxbgtBiiA

{
    "id":"1",
    "buyerId":"buyer@directdeal.co.kr"
}

###

PUT http://localhost:8083/transaction-history/setbuyer HTTP/1.1
Content-Type : application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXJAZGlyZWN0ZGVhbC5jby5rciIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjIzMzM0MDUxfQ.wP_A8Ap4Nh-3LhghhcHRlGLggOfcmdzCFfttcQLwYOY4Ye2RTbyvSzLMG6aD2p0QE4_I67R6E7g-KjxbgtBiiA

{
    "id":"2",
    "buyerId":"buyer@directdeal.co.kr"
}

###

GET http://localhost:8083/buy-history HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXJAZGlyZWN0ZGVhbC5jby5rciIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjIzMzM0MDUxfQ.wP_A8Ap4Nh-3LhghhcHRlGLggOfcmdzCFfttcQLwYOY4Ye2RTbyvSzLMG6aD2p0QE4_I67R6E7g-KjxbgtBiiA

###
DELETE http://localhost:8083/buy-history/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXJAZGlyZWN0ZGVhbC5jby5rciIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjIzMzM0MDUxfQ.wP_A8Ap4Nh-3LhghhcHRlGLggOfcmdzCFfttcQLwYOY4Ye2RTbyvSzLMG6aD2p0QE4_I67R6E7g-KjxbgtBiiA

###

GET http://localhost:8083/buy-history HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXJAZGlyZWN0ZGVhbC5jby5rciIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjIzMzM0MDUxfQ.wP_A8Ap4Nh-3LhghhcHRlGLggOfcmdzCFfttcQLwYOY4Ye2RTbyvSzLMG6aD2p0QE4_I67R6E7g-KjxbgtBiiA

###

DELETE http://localhost:8083/buy-history/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXJAZGlyZWN0ZGVhbC5jby5rciIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjIzMzM0MDUxfQ.wP_A8Ap4Nh-3LhghhcHRlGLggOfcmdzCFfttcQLwYOY4Ye2RTbyvSzLMG6aD2p0QE4_I67R6E7g-KjxbgtBiiA

###