POST http://localhost:8081/category HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXJAZGlyZWN0ZGVhbC5jby5rciIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjIzNTA2NDQwfQ.qvzYIm3Nnbi24YOjUJBu8H9vmY-XONnUnrYRtpn58Haozi9_l-r_BIQSaZYCRyfSDdVRc_AYd8h81ZSsJp4v0g

{
    "name":"Appliances"
}

###

GET http://localhost:8081/category HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXJAZGlyZWN0ZGVhbC5jby5rciIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjIzNTA2NDQwfQ.qvzYIm3Nnbi24YOjUJBu8H9vmY-XONnUnrYRtpn58Haozi9_l-r_BIQSaZYCRyfSDdVRc_AYd8h81ZSsJp4v0g

###

POST http://localhost:8081/category HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXJAZGlyZWN0ZGVhbC5jby5rciIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjIzNTA2NDQwfQ.qvzYIm3Nnbi24YOjUJBu8H9vmY-XONnUnrYRtpn58Haozi9_l-r_BIQSaZYCRyfSDdVRc_AYd8h81ZSsJp4v0g

{
    "name":"Food"
}

###

GET http://localhost:8081/category HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXJAZGlyZWN0ZGVhbC5jby5rciIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjIzNTA2NDQwfQ.qvzYIm3Nnbi24YOjUJBu8H9vmY-XONnUnrYRtpn58Haozi9_l-r_BIQSaZYCRyfSDdVRc_AYd8h81ZSsJp4v0g

###

POST http://localhost:8081/category HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzZWxsZXJAZGlyZWN0ZGVhbC5jby5rciIsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjIzNTA2NDQwfQ.qvzYIm3Nnbi24YOjUJBu8H9vmY-XONnUnrYRtpn58Haozi9_l-r_BIQSaZYCRyfSDdVRc_AYd8h81ZSsJp4v0g

{
    "name":"Computer",
    "parent": {"id":"1"}
}

###

GET http://localhost:8081/category HTTP/1.1

###

POST http://localhost:8081/category HTTP/1.1
Content-Type: application/json

{
    "name":"NoteBook",
    "parent": {"id":"3"}
}

###

GET http://localhost:8081/category HTTP/1.1

###

PUT http://localhost:8081/category HTTP/1.1
Content-Type: application/json

{
    "id":"4",
    "name":"iPad",
    "parent": {"id":"3"}
}

###

GET http://localhost:8081/category HTTP/1.1

###

PUT http://localhost:8081/category HTTP/1.1
Content-Type: application/json

{
    "id":"1",
    "name":"Appliances"
}

###

GET http://localhost:8081/category HTTP/1.1

###

DELETE http://localhost:8081/category/4 HTTP/1.1

###

GET http://localhost:8081/category HTTP/1.1

###

DELETE http://localhost:8081/category/1 HTTP/1.1

###

GET http://localhost:8081/category HTTP/1.1

###

DELETE http://localhost:8081/category/2 HTTP/1.1

###

GET http://localhost:8081/category HTTP/1.1

###