GET http://localhost:8081/item HTTP/1.1

###

POST http://localhost:8081/item HTTP/1.1
Content-Type: application/json

{
    "title":"my first item", 
    "category":"gems",
    "targetPrice":10000000000,
    "text":"my first item is gems and you can buy it now.",
    "imagePath":"/local/repository/1.png"
}

###

PUT http://localhost:8081/item HTTP/1.1
Content-Type: application/json

{
    "id":"5ea97e94-dedb-45f4-9e87-b0ea2496e1cd",
    "title":"my second item", 
    "category":"notebook",
    "targetPrice":10000000000,
    "text":"my second item is gems and you can buy it now.",
    "imagePath":"/local/repository/1.png"
}

###

DELETE http://localhost:8081/item/5ea97e94-dedb-45f4-9e87-b0ea2496e1cd HTTP/1.1

###

GET http://localhost:8082/saleitem/5ea97e94-dedb-45f4-9e87-b0ea2496e1cd HTTP/1.1

###

PUT http://localhost:8081/item HTTP/1.1
Content-Type: application/json

{
    "id":"5ea97e94-dedb-45f4-9e87-b0ea2496e1cd",
    "title":"my second item", 
    "category":"MacBook Pro M1",
    "targetPrice":10000000000,
    "text":"my second item is gems and you can buy it now.",
    "imagePath":"/local/repository/1.png"
}

###

GET http://localhost:8082/saleitem/5ea97e94-dedb-45f4-9e87-b0ea2496e1cd HTTP/1.1

###