apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  selector:
    app: kafka
  ports:
  - name: kafkaport
    port: 9092
    targetPort: 9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      version: 'v1'
  template:
    metadata:
      labels:
        app: kafka
        version: 'v1'
    spec:
      initContainers:
      - name: init-ds
        image: directdeal-registry.localhost:5000/busybox:latest
        command:
          - '/bin/sh'
          - '-c'
          - |
            while true
            do
              rt=$(nc -z -w 1 zookeeper 2181)
              if [ $? -eq 0 ]; then
                echo "DB is UP"
                break
              fi
              echo "DB is not yet reachable;sleep for 10s before retry"
              sleep 10
            done
      containers:
      - name: kafka
        image: directdeal-registry.localhost:5000/wurstmeister/kafka:2.12-2.4.1
        imagePullPolicy: Always
        ports:
        - containerPort: 9092
          name: kafkaport
        env:
          - name: KAFKA_BROKER_ID
            value: "1"
          - name: KAFKA_PORT
            value: "9092"
          - name: KAFKA_ADVERTISED_HOST_NAME
            value: "kafka"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: PLAINTEXT://kafka:9092
          - name: KAFKA_LISTENERS
            value: PLAINTEXT://:9092
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zookeeper:2181
          - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
            value: "true"
          - name: KAFKA_CREATE_TOPICS
            value: local.event:1:1
        # resources:
        #     # requests:
        #     #   memory: '512Mi'
        #     #   cpu: '500m'
        #     limits:
        #       memory: '512Mi'
        #       # cpu: '100m'
---
