apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  selector:
    app: mongo
  ports:
  - name: mongoport
    port: 27017
    targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
      version: 'v1'
  template:
    metadata:
      labels:
        app: mongo
        version: 'v1'
    spec:
      containers:
      - name: mongo
        image: directdeal-registry.localhost:5000/mongo:4.0.25
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
          name: mongoport
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: "root"
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: "secret"
        # resources:
        #     # requests:
        #     #   memory: '512Mi'
        #     #   cpu: '500m'
        #     limits:
        #       memory: '256Mi'
        #       # cpu: '100m'
---
