apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
  - name: nginxport
    port: 9000
    targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      version: 'v1'
  template:
    metadata:
      labels:
        app: nginx
        version: 'v1'
    spec:
      containers:
      - name: nginx
        image: directdeal-registry.localhost:5000/direct-deal-nginx:lastest
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
          name: nginxport
        # resources:
        #     # requests:
        #     #   memory: '512Mi'
        #     #   cpu: '500m'
        #     limits:
        #       memory: '256Mi'
        #       # cpu: '100m'
---
