spring:
    cloud:
        gateway:
            #default-filters:
            #    - name: GlobalFilter
            #    - args:
            routes:
            - id: account-controller
              uri: http://account-service:8080/
              predicates:
              - Path=/api/v1/account/**
              filters:
              - RewritePath=/api/v1(?<segment>/?.*), $\{segment} 

            - id: auth-controller
              uri: http://account-service:8080/
              predicates:
              - Path=/api/v1/auth/login
              filters:
              - RewritePath=/api/v1(?<segment>/?.*), $\{segment} 
