server:
  port: 8084

spring:
  application:
    name: direct-deal-account-service
  
  profiles:
    active:
    - route-v1

# management:
#   endpoint:
#     gateway:
#       enabled: true

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
